# Generated by Django 4.0.2 on 2022-04-09 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_uz', models.CharField(max_length=30, null=True)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('name_ru', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, default='23652806.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('name_uz', models.CharField(max_length=30, null=True)),
                ('name_en', models.CharField(max_length=30, null=True)),
                ('name_ru', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(blank=True, default='23652806.jpg', null=True, upload_to='')),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('text_uz', models.TextField(blank=True, default=None, null=True)),
                ('text_en', models.TextField(blank=True, default=None, null=True)),
                ('text_ru', models.TextField(blank=True, default=None, null=True)),
                ('comment_text', models.CharField(max_length=275)),
                ('comment_text_uz', models.CharField(max_length=275, null=True)),
                ('comment_text_en', models.CharField(max_length=275, null=True)),
                ('comment_text_ru', models.CharField(max_length=275, null=True)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('portions', models.SmallIntegerField()),
                ('how_much_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('viewed', models.BigIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.kategoriya')),
            ],
        ),
    ]
