# Generated by Django 4.0.2 on 2022-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoriya',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='text',
        ),
        migrations.AlterField(
            model_name='kategoriya',
            name='name_en',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kategoriya',
            name='name_ru',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kategoriya',
            name='name_uz',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taom',
            name='comment_text_en',
            field=models.CharField(max_length=275),
        ),
        migrations.AlterField(
            model_name='taom',
            name='comment_text_ru',
            field=models.CharField(max_length=275),
        ),
        migrations.AlterField(
            model_name='taom',
            name='comment_text_uz',
            field=models.CharField(max_length=275),
        ),
        migrations.AlterField(
            model_name='taom',
            name='name_en',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taom',
            name='name_ru',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taom',
            name='name_uz',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taom',
            name='text_en',
            field=models.TextField(default=12.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taom',
            name='text_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taom',
            name='text_uz',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
