# Generated by Django 4.0.2 on 2022-04-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_kategoriya_name_remove_taom_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taom',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taom',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taom',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
