# Generated by Django 4.0.2 on 2022-04-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_taom_text_en_alter_taom_text_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategoriya',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taom',
            old_name='comment_text_uz',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='taom',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taom',
            old_name='text_uz',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='kategoriya',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='kategoriya',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='comment_text_en',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='comment_text_ru',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='taom',
            name='text_ru',
        ),
    ]
