# Generated by Django 4.0.2 on 2022-04-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_uz_kategoriya_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriya',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='kategoriya',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='kategoriya',
            name='name_uz',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='comment_text_en',
            field=models.CharField(max_length=275, null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='comment_text_ru',
            field=models.CharField(max_length=275, null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='comment_text_uz',
            field=models.CharField(max_length=275, null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='name_uz',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taom',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
